<a href="https://colab.research.google.com/github/encore488/GuardianOwl/blob/main/correlation_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

path_to_data = '/content/renamed_PRAMS.csv'
df = pd.read_csv(path_to_data)

df.info()

df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 221381 entries, 0 to 221380
Columns: 251 entries, ID to Maternal height - feet, inches
dtypes: float64(247), object(4)
memory usage: 423.9+ MB

,"Hispanic Ethnic Group: 1=NO, 2=YES","No. of Cigarettes in 1st Trimester, Daily","No. of Cigarettes in 2nd Trimester, Daily","No. of Cigarettes in 3rd Trimester, Daily","No. of Cigarettes prior to preg, Daily","Baby was born with defect: 1=YES, 2=NO","C-section, 1st: 1=NO, 2=YES","Forceps delivery: 1=NO, 2=YES","Repeated C-section: 1=NO, 2=YES","Vacuum delivery: 1=NO, 2=YES",...,Maternal age grouped: .U=Unknown 17=17 or younger 45=45 or older,Maternal Race Asian grouped,Maternal Race Native Hawaiian Other Pacific Islander grouped,Maternal Race Multiple/Other,Maternal Race grouped: .U=UNKNOWN 2=WHITE 3=BLACK 4=AM INDIAN 10=AK NATIVE 21=ASIAN 22=HAWAIIAN/OTH PAC ISLNDR 23=OTHER/MULTIPLE RACE,Paternal Race Asian grouped,Paternal Race Native Hawaiian Other Pacific Islander grouped,Paternal Race Multiple/Other,Paternal Race grouped: .U=UNKNOWN 2=WHITE 3=BLACK 4=AM INDIAN 10=AK NATIVE 21=ASIAN 22=HAWAIIAN/OTH PACISLNDR 23=OTHER/MULTIPLE RACE,"Maternal height - feet, inches"
count,214463.000000,219896.000000,219898.000000,219900.000000,219912.000000,220156.000000,221167.000000,221207.000000,221204.000000,221207.000000,...,210829.000000,210830.000000,210831.000000,210820.000000,208923.000000,210214.000000,210215.000000,210209.000000,179439.000000,220321.000000
mean,1.175065,0.795444,0.595390,0.527372,1.257053,1.995158,1.202598,1.005963,1.128280,1.024294,...,29.238686,1.916364,1.986093,1.893947,5.891917,1.933729,1.988364,1.920279,5.479678,5.420478
std,0.380024,3.621079,3.011245,2.853222,5.027313,0.069416,0.401936,0.076988,0.334402,0.153961,...,5.757710,0.276842,0.117105,0.307906,7.667594,0.248755,0.107240,0.270861,7.376057,0.268093
min,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,17.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,2.000000,0.000000
25%,1.000000,0.000000,0.000000,0.000000,0.000000,2.000000,1.000000,1.000000,1.000000,1.000000,...,25.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,5.200000
50%,1.000000,0.000000,0.000000,0.000000,0.000000,2.000000,1.000000,1.000000,1.000000,1.000000,...,29.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,5.400000
75%,1.000000,0.000000,0.000000,0.000000,0.000000,2.000000,1.000000,1.000000,1.000000,1.000000,...,33.000000,2.000000,2.000000,2.000000,3.000000,2.000000,2.000000,2.000000,3.000000,5.600000
max,2.000000,98.000000,98.000000,98.000000,98.000000,2.000000,2.000000,2.000000,2.000000,2.000000,...,45.000000,2.000000,2.000000,2.000000,23.000000,2.000000,2.000000,2.000000,23.000000,8.000000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 221381 entries, 0 to 221380
Columns: 251 entries, ID to Maternal height - feet, inches
dtypes: float64(247), object(4)
memory usage: 423.9+ MB

,"Hispanic Ethnic Group: 1=NO, 2=YES","No. of Cigarettes in 1st Trimester, Daily","No. of Cigarettes in 2nd Trimester, Daily","No. of Cigarettes in 3rd Trimester, Daily","No. of Cigarettes prior to preg, Daily","Baby was born with defect: 1=YES, 2=NO","C-section, 1st: 1=NO, 2=YES","Forceps delivery: 1=NO, 2=YES","Repeated C-section: 1=NO, 2=YES","Vacuum delivery: 1=NO, 2=YES",...,Maternal age grouped: .U=Unknown 17=17 or younger 45=45 or older,Maternal Race Asian grouped,Maternal Race Native Hawaiian Other Pacific Islander grouped,Maternal Race Multiple/Other,Maternal Race grouped: .U=UNKNOWN 2=WHITE 3=BLACK 4=AM INDIAN 10=AK NATIVE 21=ASIAN 22=HAWAIIAN/OTH PAC ISLNDR 23=OTHER/MULTIPLE RACE,Paternal Race Asian grouped,Paternal Race Native Hawaiian Other Pacific Islander grouped,Paternal Race Multiple/Other,Paternal Race grouped: .U=UNKNOWN 2=WHITE 3=BLACK 4=AM INDIAN 10=AK NATIVE 21=ASIAN 22=HAWAIIAN/OTH PACISLNDR 23=OTHER/MULTIPLE RACE,"Maternal height - feet, inches"
count,214463.000000,219896.000000,219898.000000,219900.000000,219912.000000,220156.000000,221167.000000,221207.000000,221204.000000,221207.000000,...,210829.000000,210830.000000,210831.000000,210820.000000,208923.000000,210214.000000,210215.000000,210209.000000,179439.000000,220321.000000
mean,1.175065,0.795444,0.595390,0.527372,1.257053,1.995158,1.202598,1.005963,1.128280,1.024294,...,29.238686,1.916364,1.986093,1.893947,5.891917,1.933729,1.988364,1.920279,5.479678,5.420478
std,0.380024,3.621079,3.011245,2.853222,5.027313,0.069416,0.401936,0.076988,0.334402,0.153961,...,5.757710,0.276842,0.117105,0.307906,7.667594,0.248755,0.107240,0.270861,7.376057,0.268093
min,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,17.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,2.000000,0.000000
25%,1.000000,0.000000,0.000000,0.000000,0.000000,2.000000,1.000000,1.000000,1.000000,1.000000,...,25.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,5.200000
50%,1.000000,0.000000,0.000000,0.000000,0.000000,2.000000,1.000000,1.000000,1.000000,1.000000,...,29.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,5.400000
75%,1.000000,0.000000,0.000000,0.000000,0.000000,2.000000,1.000000,1.000000,1.000000,1.000000,...,33.000000,2.000000,2.000000,2.000000,3.000000,2.000000,2.000000,2.000000,3.000000,5.600000
max,2.000000,98.000000,98.000000,98.000000,98.000000,2.000000,2.000000,2.000000,2.000000,2.000000,...,45.000000,2.000000,2.000000,2.000000,23.000000,2.000000,2.000000,2.000000,23.000000,8.000000